name: curved_carousel
description: Curved Casrousel shows list of widgets in curve fashion.
version: 0.0.8
homepage: 'https://github.com/Mindinventory/curved_carousel'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


